server {
    listen 80;
    listen [::]:80;

    server_name mithrandir.olivierboeren.nl;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

	location /{
		return 301 https://mithrandir.olivierboeren.nl$request_uri;
	}
}

server{
	listen 443 ssl;
	listen [::]:443 ssl;
	
	server_name mithrandir.olivierboeren.nl;

	ssl_certificate /etc/nginx/ssl/live/mithrandir.olivierboeren.nl/fullchain.pem;
	ssl_certificate_key /etc/nginx/ssl/live/mithrandir.olivierboeren.nl/privkey.pem;

	location /{
		root /usr/share/nginx/html;
		try_files $uri /index.html;
	}

}
